#!/bin/sh
# 
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle startup script for POSIX generated by Gradle.
#
#   Important for running Gradle:
#   (1) You need a POSIX-compliant shell to run this script. If you don't have one
#       (e.g. you are on Windows), you should use gradlew.bat.
#   (2) The script requires `bash` to be available at `/bin/bash`.
#
##############################################################################

# Determine the Java command to use to start the JVM.
if [ -z "$JAVA_HOME" ] && [ -x "$(command -v java)" ]; then
    # Look for `java` on the PATH.
    JAVA_CMD=java
elif [ -x "$JAVA_HOME/bin/java" ]; then
    # Use JAVA_HOME if set and java exists.
    JAVA_CMD="$JAVA_HOME/bin/java"
else
    echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
    echo "Please set the JAVA_HOME variable in your environment to match the" >&2
    echo "location of your Java installation." >&2
    exit 1
fi

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Find the Gradle root.
# This script is expected to be in the same directory as `gradle`.
# If not, we try to find the root by looking up the directory tree.
GRADLE_ROOT=$(cd "$(dirname "$0")" && pwd)
while [ ! -d "$GRADLE_ROOT/gradle" ] && [ "$GRADLE_ROOT" != "/" ]; do
    GRADLE_ROOT=$(cd "$GRADLE_ROOT/.." && pwd)
done

# Check if we found the Gradle root.
if [ ! -d "$GRADLE_ROOT/gradle" ]; then
    echo "ERROR: Could not locate Gradle root directory." >&2
    exit 1
fi

# Set the Gradle user home.
if [ -z "$GRADLE_USER_HOME" ]; then
    GRADLE_USER_HOME="$HOME/.gradle"
fi

# Set the Gradle home.
if [ -z "$GRADLE_HOME" ]; then
    GRADLE_HOME="$GRADLE_ROOT"
fi

# Set the Gradle wrapper JAR.
WRAPPER_JAR="$GRADLE_HOME/gradle/wrapper/gradle-wrapper.jar"

# Check if the wrapper JAR exists.
if [ ! -f "$WRAPPER_JAR" ]; then
    echo "ERROR: Gradle wrapper JAR not found at $WRAPPER_JAR." >&2
    exit 1
fi

# Set the Gradle wrapper properties.
WRAPPER_PROPERTIES="$GRADLE_HOME/gradle/wrapper/gradle-wrapper.properties"

# Check if the wrapper properties exist.
if [ ! -f "$WRAPPER_PROPERTIES" ]; then
    echo "ERROR: Gradle wrapper properties not found at $WRAPPER_PROPERTIES." >&2
    exit 1
fi

# Set the Gradle wrapper main class.
WRAPPER_MAIN="org.gradle.wrapper.GradleWrapperMain"

# Set the JVM options.
JVM_OPTS="$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS"

# Execute the Gradle wrapper.
exec "$JAVA_CMD" $JVM_OPTS -classpath "$WRAPPER_JAR" "$WRAPPER_MAIN" "$@"
